baseURL = "https://xaviablaza.com/"
languageCode = "en-us"
title = "Xavi Ablaza"
theme = "hugo-lodi-theme"
googleAnalytics = ""
publishDir = "docs"

[params]
    theme_color = "#0B434C"
    description = "Portfolio of Xavi Ablaza, Software Engineer"
    description_photo = "portfolio.jpg"
    favicon = "favicon-x.png"
    logo = "logo-x.png"

    # if there are 6 active icons below then space them out
    space_out = true
    email = "xlablaza@gmail.com"
    facebook = "xlablaza"
#    twitter = "xaviablaza"
    keybase = "xaviablaza"
    #dribbble = ""
    linkedin = "https://www.linkedin.com/in/xaviablaza"
    medium = "xaviablaza"
    github = "xaviablaza"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Xavi, a software engineer from Manila."
    hero_right = ["**Currently a software engineering intern at [Bloom](https://bloom.solutions), a pioneer of the Bitcoin remittance industry in Manila, Philippines. Also doing consultancy work at UX Society.**", "I founded the first international chapter of the [User Experience Society](https://www.facebook.com/UXSoc/), in Orange, California. In one year, we've hosted 6 speaker events, and worked with 8 clients with our small 4-person team. We've focused on [training other students](https://medium.com/@xaviablaza/ux-society-at-chapman-university-60dc17815230) to be UX designers and front-end developers.", "I enjoy learning about devops as well. I've set up Docker image for a Rails environment that [shortened the onboarding process](https://github.com/ChapmanCPSC/CSAFE-Chapman-University) for my team in class by 1 week.", "I advocated for using [Hugo](https://gohugo.io) at UX Society to quickly turnover projects. Our process for creating landing pages from conceptualization to deployment takes no more than 5 days.", "I'm finishing my Bachelor's degree in Software Engineering at Chapman University, expecting to graduate in May 2019."]
    resume = "ResumeAblaza.pdf"

[params.process]
    enable = true
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
